version: 2

jobs:
  build:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
    - checkout
    - run:
        command: git show

notify:
  webhooks:
    - url: http://e1bd8299.ngrok.io/harbormaster/hook/circleci/
