version: 2

jobs:
  build:
    docker:
      - image: circleci/php:cli
    steps:
    - checkout
    - run:
        command: git show

notify:
  webhooks:
    - url: http://e1bd8299.ngrok.io/harbormaster/hook/circleci/
