version: 2

jobs:
  build:
    docker:
      - image: circleci/php:cli
    steps:
      - add_ssh_keys
      - checkout
      - run:
          command: git show && echo $HARBORMASTER_BUILD_TARGET_PHID

notify:
  webhooks:
    - url: http://e1bd8299.ngrok.io/harbormaster/hook/circleci/
